import type { Palette } from "./types";

// 策展配色庫 —— 每組都預先指定好 9 個語意角色,並用白話說明用途。
// 不懂色彩學的人也能直接挑、直接帶走 code。深色主題的配色 background 為深色。
export const PALETTES: Palette[] = [
  {
    id: "midnight-navy",
    name: "午夜藍",
    moods: ["沉穩專業"],
    roles: {
      background: "#f8fafc",
      surface: "#ffffff",
      text: "#0f172a",
      muted: "#475569",
      border: "#e2e8f0",
      primary: "#1e3a8a",
      primaryFg: "#ffffff",
      accent: "#0e7490",
      accentFg: "#ffffff",
    },
    blurb: "金融、法律、企業官網的安全牌。深藍給人可靠、穩重的第一印象。",
    why: "深藍配冷灰是低風險組合：彩度低、對比足,看久不累,點綴的青色帶來一點生氣又不會搶戲。",
    roleUsage: {
      primary: "主按鈕、頁首、連結 —— 想被點的東西",
      accent: "次要標籤、圖示、進度條,不要大面積用",
      background: "整頁底色,接近白但帶一點冷",
      muted: "說明文字、時間戳這類不需搶眼的字",
    },
  },
  {
    id: "graphite",
    name: "石墨灰",
    moods: ["沉穩專業", "極簡黑白"],
    roles: {
      background: "#ffffff",
      surface: "#f4f4f5",
      text: "#18181b",
      muted: "#52525b",
      border: "#e4e4e7",
      primary: "#334155",
      primaryFg: "#ffffff",
      accent: "#b45309",
      accentFg: "#ffffff",
    },
    blurb: "工具型產品、後台、文件站。中性灰當骨架,讓內容當主角。",
    why: "灰階本身沒有情緒,所以暖橘一點就跳出來。適合『內容比品牌重要』的網站。",
    roleUsage: {
      primary: "主要操作,沉穩不喧嘩",
      accent: "提醒、警示、重點數字 —— 唯一的暖色,省著用",
      surface: "卡片、側欄,跟純白底拉出層次",
    },
  },
  {
    id: "startup-orange",
    name: "電光橘",
    moods: ["活力新創"],
    roles: {
      background: "#fffbf5",
      surface: "#ffffff",
      text: "#1c1917",
      muted: "#57534e",
      border: "#f0e9e0",
      primary: "#ea580c",
      primaryFg: "#ffffff",
      accent: "#0d9488",
      accentFg: "#ffffff",
    },
    blurb: "新創 landing、活動頁、號召行動。橘色有衝勁,逼人想點。",
    why: "橘配青是『對比互補』:色輪上幾乎相對,放一起最搶眼。一個當主角、一個當配角才不會打架。",
    roleUsage: {
      primary: "CTA 大按鈕『立即註冊』那種",
      accent: "次要連結、成功狀態,平衡橘色的躁",
      background: "帶一點奶油的暖白,比純白親切",
    },
  },
  {
    id: "berry-pop",
    name: "莓果紫",
    moods: ["活力新創", "柔和粉嫩"],
    roles: {
      background: "#faf5ff",
      surface: "#ffffff",
      text: "#1e1b2e",
      muted: "#5b5270",
      border: "#ece4f5",
      primary: "#7c3aed",
      primaryFg: "#ffffff",
      accent: "#db2777",
      accentFg: "#ffffff",
    },
    blurb: "創作者工具、社群、訂閱服務。紫配粉年輕、有個性。",
    why: "紫和粉是『相鄰色』,色輪上靠很近,所以和諧不衝突,整體調性統一又活潑。",
    roleUsage: {
      primary: "品牌主色,按鈕與重點",
      accent: "愛心、通知、強調標籤",
    },
  },
  {
    id: "pure-mono",
    name: "純粹",
    moods: ["極簡黑白"],
    roles: {
      background: "#ffffff",
      surface: "#fafafa",
      text: "#0a0a0a",
      muted: "#525252",
      border: "#e5e5e5",
      primary: "#0a0a0a",
      primaryFg: "#ffffff",
      accent: "#404040",
      accentFg: "#ffffff",
    },
    blurb: "作品集、攝影、精品。黑白讓作品本身說話。",
    why: "完全沒有顏色就不會出錯,也最考驗排版。留白與字級的層次就是設計。",
    roleUsage: {
      primary: "黑色按鈕,極簡又有份量",
      muted: "灰字做次要資訊,靠深淺分層級",
    },
  },
  {
    id: "dark-mono",
    name: "暗夜",
    moods: ["極簡黑白", "科技未來"],
    roles: {
      background: "#0a0a0a",
      surface: "#171717",
      text: "#fafafa",
      muted: "#a3a3a3",
      border: "#262626",
      primary: "#fafafa",
      primaryFg: "#0a0a0a",
      accent: "#a3a3a3",
      accentFg: "#0a0a0a",
    },
    blurb: "開發者工具、深色介面、夜間閱讀。黑底白字俐落專注。",
    why: "深色主題重點是『不要純黑配純白』—— 用接近黑的灰當底、接近白的灰當字,刺眼感會降很多。",
    roleUsage: {
      background: "近黑(非純黑)當頁底,長時間看不累",
      surface: "卡片用更亮一階的深灰,堆疊出層次",
      primary: "亮色按鈕,在暗底上自然成為焦點",
    },
  },
  {
    id: "forest",
    name: "森林",
    moods: ["自然有機"],
    roles: {
      background: "#f7f9f4",
      surface: "#ffffff",
      text: "#1a2417",
      muted: "#4d5a44",
      border: "#e3ead9",
      primary: "#2f6b3c",
      primaryFg: "#ffffff",
      accent: "#a16207",
      accentFg: "#ffffff",
    },
    blurb: "有機食品、戶外品牌、永續主題。綠色直覺聯想到天然、健康。",
    why: "綠配大地棕是『自然界本來就有的搭配』,看了安心。彩度都壓低一點才有質樸感。",
    roleUsage: {
      primary: "品牌綠,按鈕與標題",
      accent: "土黃點綴,像泥土與麥稈",
    },
  },
  {
    id: "terracotta",
    name: "土壤",
    moods: ["自然有機", "溫暖親切"],
    roles: {
      background: "#faf6f0",
      surface: "#ffffff",
      text: "#2b1f17",
      muted: "#6b5847",
      border: "#ece0d2",
      primary: "#92400e",
      primaryFg: "#ffffff",
      accent: "#4d7c0f",
      accentFg: "#ffffff",
    },
    blurb: "手作、陶藝、咖啡、生活風格。陶土色溫潤、有手感。",
    why: "暖棕當主色給人踏實溫暖的感覺,配一點橄欖綠像植物,整體像一間有質感的小店。",
    roleUsage: {
      primary: "陶土棕,主要按鈕與標題",
      accent: "橄欖綠,自然系的點綴",
    },
  },
  {
    id: "ink-gold",
    name: "墨金",
    moods: ["優雅奢華", "極簡黑白"],
    roles: {
      background: "#0c0a09",
      surface: "#1c1917",
      text: "#faf9f7",
      muted: "#a8a29e",
      border: "#292524",
      primary: "#c5a253",
      primaryFg: "#1c1207",
      accent: "#f5e9cf",
      accentFg: "#1c1207",
    },
    blurb: "精品、珠寶、高端餐飲。黑配金是奢華感的標準答案。",
    why: "深色背景讓金色像在發光,少即是多 —— 金色只點在最關鍵的地方,貴氣才出得來。",
    roleUsage: {
      background: "近黑底,襯托金色",
      primary: "香檳金,按鈕與品牌標記",
      accent: "更淡的米金,做高光與分隔",
    },
  },
  {
    id: "bordeaux",
    name: "酒紅",
    moods: ["優雅奢華"],
    roles: {
      background: "#fdf8f8",
      surface: "#ffffff",
      text: "#2a1518",
      muted: "#6e4a4f",
      border: "#ecdcdd",
      primary: "#7f1d1d",
      primaryFg: "#ffffff",
      accent: "#a16207",
      accentFg: "#ffffff",
    },
    blurb: "酒莊、高級餐廳、成熟品牌。深酒紅成熟、有底蘊。",
    why: "暗紅彩度低、明度也低,所以顯得內斂沉穩,不是廉價的鮮紅。配金更顯格調。",
    roleUsage: {
      primary: "酒紅,主視覺與按鈕",
      accent: "金棕,稀少地點綴",
    },
  },
  {
    id: "peach-soft",
    name: "蜜桃",
    moods: ["柔和粉嫩", "溫暖親切"],
    roles: {
      background: "#fff7f4",
      surface: "#ffffff",
      text: "#3a2420",
      muted: "#8a6a62",
      border: "#f6e3db",
      primary: "#e0567a",
      primaryFg: "#ffffff",
      accent: "#f59e0b",
      accentFg: "#3a2420",
    },
    blurb: "美妝、甜點、女性向品牌。蜜桃粉甜美、溫柔。",
    why: "低彩度的粉不會太膩,配上暖黃像水果,給人愉悅放鬆的感覺。",
    roleUsage: {
      primary: "蜜桃粉,按鈕與重點",
      accent: "暖黃,用深色字才看得清",
    },
  },
  {
    id: "lavender",
    name: "薰衣草",
    moods: ["柔和粉嫩"],
    roles: {
      background: "#faf8ff",
      surface: "#ffffff",
      text: "#2c2640",
      muted: "#6f6790",
      border: "#e9e3f5",
      primary: "#8b5cf6",
      primaryFg: "#ffffff",
      accent: "#ec4899",
      accentFg: "#ffffff",
    },
    blurb: "冥想、香氛、療癒系 app。薰衣草紫平靜、舒緩。",
    why: "柔紫加亮粉是相鄰色的甜美組合,彩度適中所以溫柔又不無聊。",
    roleUsage: {
      primary: "薰衣草紫,主色調",
      accent: "亮粉,做愛心、強調",
    },
  },
  {
    id: "cyber-blue",
    name: "賽博藍",
    moods: ["科技未來"],
    roles: {
      background: "#0a0f1e",
      surface: "#131a2e",
      text: "#e8eefc",
      muted: "#8b9bc4",
      border: "#1e2845",
      primary: "#3b82f6",
      primaryFg: "#07101f",
      accent: "#22d3ee",
      accentFg: "#07101f",
    },
    blurb: "SaaS、AI 產品、儀表板。深藍底配亮藍青,科技感十足。",
    why: "深色底上用高彩度的藍與青,像螢幕在發光,點綴處最吸睛,很適合數據型產品。",
    roleUsage: {
      background: "深海軍藍底,沉浸又專注",
      primary: "亮藍按鈕,在暗底上發光",
      accent: "青色,圖表高亮、即時狀態",
    },
  },
  {
    id: "neon-night",
    name: "霓虹",
    moods: ["科技未來", "活力新創"],
    roles: {
      background: "#0d0d12",
      surface: "#18181f",
      text: "#f0f0f5",
      muted: "#9595a5",
      border: "#26262f",
      primary: "#6366f1",
      primaryFg: "#ffffff",
      accent: "#059669",
      accentFg: "#ffffff",
    },
    blurb: "遊戲、串流、夜生活主題。暗底配霓虹色,炫又有個性。",
    why: "近黑底讓飽和的靛紫與翠綠像霓虹燈管,對比強烈,適合想要『酷』的場景。",
    roleUsage: {
      primary: "靛紫,主要互動",
      accent: "翠綠,成功與點綴",
    },
  },
  {
    id: "warm-sun",
    name: "暖陽",
    moods: ["溫暖親切"],
    roles: {
      background: "#fffaf2",
      surface: "#ffffff",
      text: "#2e2113",
      muted: "#7a6444",
      border: "#f3e7d2",
      primary: "#d97706",
      primaryFg: "#ffffff",
      accent: "#dc2626",
      accentFg: "#ffffff",
    },
    blurb: "餐飲、烘焙、親子。暖橘暖紅讓人有食慾、有溫度。",
    why: "全暖色調(橘+紅)營造熱情友善的氛圍,像陽光下的市集,適合想拉近距離的品牌。",
    roleUsage: {
      primary: "暖橘,主要按鈕",
      accent: "暖紅,限時、優惠這種要熱度的地方",
    },
  },
  {
    id: "milk-tea",
    name: "奶茶",
    moods: ["溫暖親切", "自然有機"],
    roles: {
      background: "#faf6f1",
      surface: "#ffffff",
      text: "#2d241b",
      muted: "#6f6051",
      border: "#ece1d4",
      primary: "#a16207",
      primaryFg: "#ffffff",
      accent: "#0f766e",
      accentFg: "#ffffff",
    },
    blurb: "飲料、文具、生活雜貨。奶茶色溫和、耐看、好親近。",
    why: "低彩度的焦糖棕當底很『日系』,配一點墨綠提神,整體溫吞但不平淡。",
    roleUsage: {
      primary: "焦糖棕,品牌主色",
      accent: "墨綠,平衡暖色、做點綴",
    },
  },
  {
    id: "steel-blue",
    name: "鋼藍",
    moods: ["沉穩專業", "科技未來"],
    roles: {
      background: "#f6f8fa",
      surface: "#ffffff",
      text: "#11212e",
      muted: "#4a5d6b",
      border: "#dde6ec",
      primary: "#0f4c75",
      primaryFg: "#ffffff",
      accent: "#b91c1c",
      accentFg: "#ffffff",
    },
    blurb: "B2B、製造業、技術文件。鋼藍冷靜、精準、可信。",
    why: "偏冷的藍給人精密、理性的印象,配一抹紅當警示色,層級很清楚。",
    roleUsage: {
      primary: "鋼藍,主要操作與標題",
      accent: "警示紅,錯誤、刪除、重點提醒",
    },
  },
  {
    id: "citrus",
    name: "檸檬萊姆",
    moods: ["活力新創", "自然有機"],
    roles: {
      background: "#fdfff5",
      surface: "#ffffff",
      text: "#1f2410",
      muted: "#545c3a",
      border: "#e8eed2",
      primary: "#4d7c0f",
      primaryFg: "#ffffff",
      accent: "#ea580c",
      accentFg: "#ffffff",
    },
    blurb: "健康、運動、果汁飲品。萊姆綠清新、有活力。",
    why: "黃綠色給人新鮮、健康的聯想,配上橘像柑橘類水果,整體清爽有精神。",
    roleUsage: {
      primary: "萊姆綠,主色與按鈕",
      accent: "橘,號召與重點",
    },
  },
  {
    id: "ocean",
    name: "海洋",
    moods: ["自然有機", "沉穩專業"],
    roles: {
      background: "#f2fafb",
      surface: "#ffffff",
      text: "#0e2426",
      muted: "#3f5d60",
      border: "#d6e9eb",
      primary: "#0e7490",
      primaryFg: "#ffffff",
      accent: "#ca8a04",
      accentFg: "#1a1505",
    },
    blurb: "旅遊、海洋保育、水上活動。藍綠像海水,清涼放鬆。",
    why: "青藍讓人想到海與天,療癒又乾淨,配一點沙金像海灘,主題感很強。",
    roleUsage: {
      primary: "海青色,主視覺",
      accent: "沙金,用深色字才清楚",
    },
  },
  {
    id: "emerald-lux",
    name: "翡翠綠",
    moods: ["優雅奢華", "自然有機"],
    roles: {
      background: "#f5faf7",
      surface: "#ffffff",
      text: "#0c2018",
      muted: "#3f5c4f",
      border: "#d8e8df",
      primary: "#065f46",
      primaryFg: "#ffffff",
      accent: "#a16207",
      accentFg: "#ffffff",
    },
    blurb: "精品旅宿、保養品、高端服務。墨綠沉穩中帶貴氣。",
    why: "深翡翠綠彩度高但明度低,顯得高級而不刺眼,配金棕更顯精緻。",
    roleUsage: {
      primary: "翡翠綠,品牌主色",
      accent: "金棕,點綴奢華感",
    },
  },
  {
    id: "mint",
    name: "薄荷",
    moods: ["柔和粉嫩", "自然有機"],
    roles: {
      background: "#f4fbf8",
      surface: "#ffffff",
      text: "#14271f",
      muted: "#4c6258",
      border: "#dbeee6",
      primary: "#0d9488",
      primaryFg: "#ffffff",
      accent: "#f472b6",
      accentFg: "#3a1525",
    },
    blurb: "健康 app、牙醫、清潔用品。薄荷綠乾淨、清爽、有信任感。",
    why: "薄荷綠給人潔淨健康的印象,配一點亮粉增加親和力,冷暖平衡剛好。",
    roleUsage: {
      primary: "薄荷綠,主色與按鈕",
      accent: "亮粉,深色字確保可讀",
    },
  },
  {
    id: "deep-space",
    name: "深空紫",
    moods: ["科技未來", "優雅奢華"],
    roles: {
      background: "#100a1e",
      surface: "#1c1430",
      text: "#ece6fb",
      muted: "#9a8cc4",
      border: "#2c2147",
      primary: "#a855f7",
      primaryFg: "#15082a",
      accent: "#38bdf8",
      accentFg: "#07121f",
    },
    blurb: "AI、加密、未來科技。深紫底配亮紫天藍,神秘又高級。",
    why: "暗紫當底很有未來與神秘感,亮紫和天藍在上面像星雲,很適合想要前衛形象的產品。",
    roleUsage: {
      background: "深空紫底,沉浸感",
      primary: "亮紫按鈕,焦點所在",
      accent: "天藍,高亮與連結",
    },
  },
  {
    id: "coral",
    name: "珊瑚",
    moods: ["溫暖親切", "活力新創"],
    roles: {
      background: "#fff6f4",
      surface: "#ffffff",
      text: "#331c17",
      muted: "#7d574d",
      border: "#f5ddd6",
      primary: "#e2502f",
      primaryFg: "#ffffff",
      accent: "#0d9488",
      accentFg: "#ffffff",
    },
    blurb: "社群、活動、年輕品牌。珊瑚橘紅熱情、好記。",
    why: "珊瑚色介於紅與橘之間,比純紅柔、比純橘有個性,配青綠的互補色更跳。",
    roleUsage: {
      primary: "珊瑚紅,主要 CTA",
      accent: "青綠,冷色平衡熱度",
    },
  },
  {
    id: "newsprint",
    name: "報紙",
    moods: ["極簡黑白", "優雅奢華"],
    roles: {
      background: "#faf9f6",
      surface: "#ffffff",
      text: "#1a1a18",
      muted: "#57564f",
      border: "#e6e4dc",
      primary: "#1a1a18",
      primaryFg: "#faf9f6",
      accent: "#b91c1c",
      accentFg: "#ffffff",
    },
    blurb: "媒體、部落格、長文閱讀。米白報紙感,專注閱讀。",
    why: "微暖的米白底比純白柔和、適合長時間閱讀,黑字配一點紅當重點,像經典報刊。",
    roleUsage: {
      background: "米白底,降低閱讀疲勞",
      primary: "近黑,標題與按鈕",
      accent: "報導紅,重點與分類標籤",
    },
  },
];

export function getPalette(id: string): Palette | undefined {
  return PALETTES.find((p) => p.id === id);
}
