// UI 文案集中一處,未來要加英文 i18n 時從這裡長 locale。
export const t = {
  appName: "Style Explorer",
  tagline: "給沒學過色彩學的人,也能挑到能用的配色",
  intro:
    "選一組配色,即時看它套到真實版型的樣子,讀懂為什麼好看,然後一鍵帶走 code。",
  filterAll: "全部",
  filterLabel: "風格",
  wcagLabel: "可讀性",
  wcagAll: "不限",
  wcagAA: "AA+",
  wcagAAA: "AAA",
  paletteCount: (n: number) => `${n} 組`,
  generate: "產生新配色",
  generateHint: "依目前可讀性條件動態生成,保證達標",
  generatedTag: "動態",
  empty: "沒有符合條件的配色,換個篩選或按上面「產生新配色」",
  preview: {
    landing: "Landing 頁",
    blog: "部落格",
    dashboard: "儀表板",
    ecommerce: "電商",
    form: "表單",
    label: "版型",
    colorblind: "色覺",
    cbNormal: "正常",
  },
  info: {
    scene: "適合什麼情境",
    why: "為什麼這樣搭好看",
    roles: "每個顏色用在哪",
    contrast: "可讀性檢查(WCAG)",
    contrastHint: "文字疊在底色上夠不夠清楚。AA 是基本門檻,AAA 更安全。",
    export: "匯出這組配色",
    customTag: "已自訂",
    fixAA: "一鍵修到 AA",
    fixAAA: "一鍵修到 AAA",
    fixHint: "自動就近微調不達標的顏色,讓它過關。",
    edit: "微調顏色",
    editHint: "點色塊改顏色,即時看預覽與對比。",
    share: "複製分享連結",
    shared: "連結已複製!",
  },
  contrast: {
    textOnBg: "內文 / 頁底",
    textOnSurface: "內文 / 卡片",
    primary: "主色按鈕文字",
    accent: "強調色文字",
  },
  exportModal: {
    title: "匯出配色",
    css: "CSS",
    tailwind: "Tailwind",
    scss: "SCSS",
    json: "JSON",
    copy: "複製",
    copied: "已複製!",
    close: "關閉",
    cssHint: "貼進你的全域 CSS,用 var(--color-primary) 等引用。",
    twHint: "貼進 globals.css,即可使用 bg-primary、text-surface 等 utility。",
    scssHint: "貼進你的 .scss,用 $color-primary 等引用。",
    jsonHint: "W3C Design Tokens 格式,Figma Tokens / Style Dictionary 可直接吃。",
  },
  theory: {
    title: "順便懂一點色彩學",
    subtitle: "不背術語,看例子就好",
  },
  roleNames: {
    background: "頁底",
    surface: "卡片底",
    text: "主文字",
    muted: "次要文字",
    border: "邊框",
    primary: "主色",
    primaryFg: "主色上的字",
    accent: "強調色",
    accentFg: "強調色上的字",
  } as Record<string, string>,
};
